name: CodSpeed

on: workflow_dispatch

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    defaults:
      run:
        working-directory: ./src/app

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies 
        run: make deps

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest ./src/app/test/ --codspeed --ignore=./src/app/test/api/ --ignore=./src/app/test/topic_test.py --ignore=./src/app/test/user_test.py --ignore=./src/app/test/api/http/unit/handlers/v1/users_test.py --ignore=./src/app/test/db/mongo/models_test.py --ignore=./src/app/test/api/http/unit/handlers/v1/event_test.py --ignore=./src/app/test/api/http/unit/handlers/v1/event_test.py --ignore=./src/app/test/api/http/unit/handlers/v1/job_test.py --ignore=./src/app/test/authorization_test.py --ignore=./src/app/test/config_test.py --ignore=./src/app/test/events/handlers_test.py --ignore=./src/app/test/local_plugins/env_help_test.py --ignore=./src/app/test/local_plugins/manager_test.py --ignore=./src/app/test/local_plugins/runner_test.py --ignore=./src/app/test/metrics_test.py --ignore=./src/app/test/queues/rabbit_test.py --ignore=./src/app/test/requests_test.py --ignore=./src/app/test/role_test.py
